version: "3.7"
services:
  sa_api_compose:
    build: .
    container_name: suivie_academique_app
    restart: always
    ports:
      - "8084:8089" # Accès via http://localhost:8084
    networks:
      - sa_net
    environment:
      # On force le profil de config (ex: dev) si nécessaire
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/sa_api_db?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
    depends_on:
      - mysqldb

  mysqldb:
    image: "mysql:8.0"
    container_name: suivie_academique_db
    restart: always
    ports:
      - "3308:3306" # Accès à la DB depuis votre PC via le port 3308
    networks:
      - sa_net
    environment:
      MYSQL_DATABASE: sa_api_db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql

networks:
  sa_net:

volumes:
  mysql_data: # Pour ne pas perdre vos données si vous éteignez le conteneur